Image info and Customer Setup page introduced to the project environment.
anaikarsaad/beaware pull request #5
Opened 2024-02-29 12:24 UTC by AnshAggarwalMAC

Please review the changes :
<img width="975" alt="Screenshot 2024-02-29 at 5 20 00 AM" src="https://github.com/anaikarsaad/beaware/assets/134725638/624cc336-ddd5-4342-9320-113da630e76f">
<img width="978" alt="Screenshot 2024-02-29 at 6 39 59 AM" src="https://github.com/anaikarsaad/beaware/assets/134725638/bc27ab42-7ef5-4636-bdaf-4973a2a63cf1">

<img width="1438" alt="Screenshot 2024-02-29 at 7 23 22 AM" src="https://github.com/anaikarsaad/beaware/assets/134725638/24a9d695-1397-49a2-917f-231a94d14b45">
<img width="1440" alt="Screenshot 2024-02-29 at 7 23 56 AM" src="https://github.com/anaikarsaad/beaware/assets/134725638/7ea1337a-7926-40d2-b96b-24a9d2d0bb94">

2024-02-29 16:11 UTC, AnshAggarwalMAC commented
![image](https://github.com/anaikarsaad/beaware/assets/134725638/99731e52-09d1-4794-915f-5ba20d052287)
<img width="1440" alt="Screenshot 2024-02-29 at 11 10 10 AM" src="https://github.com/anaikarsaad/beaware/assets/134725638/e536c02b-93c9-4bb1-9541-7d56c978dfad">

2024-03-01 13:55 UTC, anaikarsaad requested changes
Wrong pages done

2024-03-01 13:55 UTC, anaikarsaad commented on src/pages/CompanionSetup.tsx
Wrong file

2024-03-01 13:55 UTC, anaikarsaad commented on src/pages/ImageInfo.tsx
Wrong page

2024-03-01 13:55 UTC, anaikarsaad commented on src/pages/YourImages.tsx
Wrong page

2024-03-01 13:55 UTC, anaikarsaad commented
Wrong screens

2024-03-01 13:55 UTC, closed without merging